tools: fix rest of the golangci-lint warnings
internal/parser/validate.go:235:12: Error return value of `group.Wait` is not checked (errcheck)
internal/parser/validate.go:250:12: Error return value of `group.Wait` is not checked (errcheck)
internal/parser/write.go:20:14: Error return value of `fmt.Fprintf` is not checked (errcheck)
internal/parser/write.go:75:14: Error return value of `fmt.Fprintf` is not checked (errcheck)
newgtlds.go:345:23: Error return value of `resp.Body.Close` is not checked (errcheck)
newgtlds_test.go:553:17: Error return value of `os.Remove` is not checked (errcheck)
newgtlds_test.go:561:17: Error return value of `os.Remove` is not checked (errcheck)
newgtlds_test.go:573:17: Error return value of `os.Remove` is not checked (errcheck)
newgtlds_test.go:583:17: Error return value of `os.Remove` is not checked (errcheck)
newgtlds_test.go:593:17: Error return value of `os.Remove` is not checked (errcheck)
newgtlds_test.go:668:16: Error return value of `fmt.Fprintln` is not checked (errcheck)
internal/parser/clean.go:421:2: S1011: should replace loop with out.Text = append(out.Text, inf.Other...) (staticcheck)
internal/parser/diff.go:266:7: S1002: should omit comparison to bool constant, can be simplified to !b.info().isUnchanged (staticcheck)
internal/parser/errors.go:24:59: QF1008: could remove embedded field "SourceRange" from selector (staticcheck)
internal/parser/errors.go:34:84: QF1008: could remove embedded field "SourceRange" from selector (staticcheck)
internal/parser/errors.go:44:79: QF1008: could remove embedded field "SourceRange" from selector (staticcheck)
internal/parser/errors.go:56:74: QF1008: could remove embedded field "SourceRange" from selector (staticcheck)
internal/parser/errors.go:67:69: QF1008: could remove embedded field "SourceRange" from selector (staticcheck)
internal/parser/errors.go:79:72: QF1008: could remove embedded field "SourceRange" from selector (staticcheck)
internal/parser/errors.go:90:61: QF1008: could remove embedded field "SourceRange" from selector (staticcheck)
internal/parser/errors.go:100:70: QF1008: could remove embedded field "SourceRange" from selector (staticcheck)
internal/parser/errors.go:110:73: QF1008: could remove embedded field "SourceRange" from selector (staticcheck)
internal/parser/errors.go:122:52: QF1008: could remove embedded field "SourceRange" from selector (staticcheck)
internal/parser/errors.go:130:72: QF1008: could remove embedded field "SourceRange" from selector (staticcheck)
internal/parser/errors.go:138:75: QF1008: could remove embedded field "SourceRange" from selector (staticcheck)
internal/parser/exceptions.go:32:2: S1008: should use 'return missingTXT.Has(domain.String())' instead of 'if missingTXT.Has(domain.String()) { return true }; return false' (staticcheck)
internal/parser/parser.go:266:8: QF1008: could remove embedded field "SourceRange" from selector (staticcheck)
internal/parser/parser.go:419:26: QF1008: could remove embedded field "SourceRange" from selector (staticcheck)
internal/parser/exceptions.go:25:6: func exemptFromSorting is unused (unused)
internal/parser/exceptions.go:77:5: var incorrectSort is unused (unused)

Signed-off-by: Sami Kerola <kerolasa@cloudflare.com>